### ISSUE TITLE
Мелкие исправления

### ISSUE THREAD

**Issue by Bobogok** [qurias/computer_courses#2]
https://github.com/qurias/computer_courses/blob/4ab21935d51b1c8e58acdf20def09e40bc76be33/public/index.html#L88-L92

Заметил, что ты  ставишь слишком много `<br />` там, где в принципе это не нужно, не только в этом месте кода. Когда текст можно ограничить шириной блока его родителя - всегда используй это вместо `<br />`

Приведу пример, где `<br />` был вполне обоснованным. Здесь бессмысленно задавать ширину родителя, т.к выше у тебя есть тайтл, который сжимать не желательно.
https://github.com/qurias/computer_courses/blob/4ab21935d51b1c8e58acdf20def09e40bc76be33/public/index.html#L311

Выводы: если будешь в следующий раз использовать `<br />` то подумай, а нужен ли он вообще здесь 🤔🤔🤔

**Comment by Bobogok** [comment]
Сделай это **отдельным** файлом

https://github.com/qurias/computer_courses/blob/4ab21935d51b1c8e58acdf20def09e40bc76be33/src/scss/_global.scss#L30-L59

**Comment by qurias** [comment]
На счет <br /> хорошее объяснение , на счет отдельного файла, я что-то позабыл его добавить в отдельный файл
